### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by cboxgo69** [thk-cheng/lbry_batch_uploader#47]
I run the following command with the values being a) full path to folder containing an mp4 file, b) the channel name, and c) a list of tags as quoted values:

```
python3 -m lbry_batch_uploader \
    "$input_folder" \
    "@${channel}" \
    --bid 0.001 \
    --fee-amount 0.00 \
    --languages "en" \
    --optimize-file \
    --port 5279 \
    --tags $tags
```

And get the following error:

```
ffmpeg is not configured properly.--optimize-file set to False.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/__main__.py", line 11, in <module>
    uploader.upload_all_files()
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 78, in upload_all_files
    claim_id = self._upload_file(file_params)
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 172, in _upload_file
    req_result: dict = self._get_req_info(req_json, "result")
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 104, in _get_req_info
    raise e from None
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 98, in _get_req_info
    req_info: dict = req_json[info_type]
KeyError: 'result'
```

Any thoughts to what might not be configured correctly?  I'm on MacOSX.

**Comment by thk-cheng** [comment]
I think I have managed to reproduce the error, please give me some time to investigate.

**Comment by cboxgo69** [comment]
Thanks for responding promptly.  I wonder, what happens if a video already exists... is it uploaded twice, written over, or skipped?

**Comment by cboxgo69** [comment]
By the way, I used the following commands:

```
python3 -m lbry_batch_uploader \
    "$input_folder" \
    "@${channel}" \
    --bid 0.001 \
    --fee-amount 0.00 \
    --languages "en" \
    --license "Public Domain" \
    --optimize-file \
    --port 5279 \
    --tags $tags

```

And go the following response:

```
ffmpeg is not configured properly.--optimize-file set to False.
Sucessfully uploaded Weekly Highlights - 2022-06-13.mp4
The claim id is ...
The claim url is lbry://WeeklyHighlights-2022-06-13 ...
```

It seems to ignore the FFMPEG warning, but I wonder a few things: 1) how can I configure FFMPEG to work without warnings, 2) how do I make this visible on Odysee, 3) is there room for things like playlist and description to be added to the loader?  This, of course, in addition to my earlier question regarding handling duplicate uploads.

**Comment by thk-cheng** [comment]
> Thanks for responding promptly. I wonder, what happens if a video already exists... is it uploaded twice, written over, or skipped?

I just tested, the original file would be overwritten, the claim id is the same.
![Screenshot 2022-06-13 at 16 43 10](https://user-images.githubusercontent.com/71027661/173392347-4e635b55-3176-4386-902c-2ec74374426c.png)
![Screenshot 2022-06-13 at 16 43 58](https://user-images.githubusercontent.com/71027661/173393263-439b3bde-8d63-42be-9938-985c8f90eea6.png)

**Comment by cboxgo69** [comment]
Okay, so what i'm doing is a migration tool and I'm passing everything off to your tool.  This is really helpful because I can already download a channel, playlist, or video along with a description file, so this is all pretty easy to integrate.  As for playlist, I'll just stay tuned I guess for updates.  Thanks.

**Comment by thk-cheng** [comment]
Good to hear that :)
I will close this issue for now as the main problem is fixed by #48

**Comment by thk-cheng** [comment]
Good to hear that :)
I will close this issue for now as the main problem is fixed by #48

**Comment by cboxgo69** [comment]
Strangely, I'm getting KeyError again.

**Comment by thk-cheng** [comment]
Could you provide the traceback again?
There should also be a line starting with "Error msg from lbrynet api:" just before the traceback if you are using the latest version (v1.1.0), it would be helpful to grab that line as well.

**Comment by cboxgo69** [comment]
I used the --optimize-file parameter and it failed, then when I took it out it worked.  This is the output :

```
(venv) (base) cboxgo@MacOSX Video-Tools % python3 -m lbry_batch_uploader "/Users/cboxgo/ClipGrabDownloads/_upload_test/_tutorials/" "@BearcatJamboree" --bid 0.001 --fee-amount 0.00 --languages "en" --license "Copyrighted (All rights reserved)" --port 5279 --tags "Minecraft" "Gaming" "Shorts" --optimize-file
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/__main__.py", line 11, in <module>
    uploader.upload_all_files()
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 78, in upload_all_files
    claim_id = self._upload_file(file_params)
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 172, in _upload_file
    req_result: dict = self._get_req_info(req_json, "result")
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 104, in _get_req_info
    raise e from None
  File "/opt/homebrew/lib/python3.9/site-packages/lbry_batch_uploader/uploader.py", line 98, in _get_req_info
    req_info: dict = req_json[info_type]
KeyError: 'result'
```

However, it looks like it fails either way... like it was just random that it worked before.  Maybe there is something weird about the video this time or in my environment that doesn't always fail.

**Comment by cboxgo69** [comment]
This is basically what I'm generating in my script:

`python3 -m lbry_batch_uploader "/Users/cboxgo/ClipGrabDownloads/_upload_test/_tutorials/" "@BearcatJamboree" --bid 0.001 --fee-amount 0.00 --languages "en" --license "Copyrighted (All rights reserved)" --port 5279 --tags "Minecraft" "Gaming" "Shorts"
`

Anything look obviously wrong?

**Comment by thk-cheng** [comment]
I have a feeling the `--license` option was causing the error again. I will come back to you soon.
`--optimize-file` probably is not the culprit here but I will also look into that as well.

**Comment by thk-cheng** [comment]
Could you run `pip install -U lbry_batch_uploader` in your environemnt, then run `pip freeze` to make sure you see `lbry-batch-uploader==1.1.0` and try again? I would like to see the error message returned by the lbrynet api, it should appear right before the traceback.

**Comment by cboxgo69** [comment]
I did the install and here is the freeze output:

```
(base) xxxxxx@MacOSX ~ % pip freeze |grep lbry
lbry-batch-uploader==1.1.0
```

**Comment by cboxgo69** [comment]
I forgot to ask, is there an option for Thumbnail?  If not, then that's okay, I thought I would check anyway...

**Comment by thk-cheng** [comment]
Yeah probably you don't even fund to cover the transaction...
Even if we set `bid` to its minimum (i.e. 0.0001, which is the default already), the transaction fee is still there and it's fluctuating daily together with the LBC. I think there might be ways to estimate the fee for each upload but it is not that straight forward.

**Comment by thk-cheng** [comment]
> I forgot to ask, is there an option for Thumbnail? If not, then that's okay, I thought I would check anyway...

Yes, this is also what I forgot to document in README.md along with the description.
The uploader would again scan the folder and find the file that has the same name as the video, but with an extension of either  ".gif", ".jpg" or ".png".

**Comment by cboxgo69** [comment]
This is all helpful.  Thanks!
